import {
  Accessibility,
  AirVent,
  Armchair,
  Bath,
  BedDouble,
  Building2,
  Car,
  Check,
  Coffee,
  ConciergeBell,
  CookingPot,
  Croissant,
  CupSoda,
  Dumbbell,
  Flame,
  KeyRound,
  Lamp,
  Plane,
  Phone,
  Refrigerator,
  ShowerHead,
  Sparkles,
  Sun,
  Thermometer,
  Tv,
  Users,
  UtensilsCrossed,
  VolumeX,
  WashingMachine,
  Waves,
  Wifi,
  Wine,
  Clock,
  ArrowUpDown,
  CigaretteOff,
  Presentation,
  Footprints,
  Wind,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  wifi: Wifi,
  parking: Car,
  airport_shuttle: Plane,
  restaurant: UtensilsCrossed,
  bar: Wine,
  breakfast: Croissant,
  room_service: ConciergeBell,
  reception_24h: Clock,
  elevator: ArrowUpDown,
  fitness: Dumbbell,
  pool: Waves,
  spa: Sparkles,
  sauna: Flame,
  hammam: Bath,
  family_rooms: Users,
  accessible: Accessibility,
  non_smoking: CigaretteOff,
  laundry: WashingMachine,
  meeting_rooms: Presentation,
  terrace: Sun,
  concierge: KeyRound,
  private_bathroom: ShowerHead,
  ac: AirVent,
  heating: Thermometer,
  tv: Tv,
  minibar: CupSoda,
  fridge: Refrigerator,
  kettle: CookingPot,
  coffee_machine: Coffee,
  safe: KeyRound,
  hairdryer: Wind,
  shower: ShowerHead,
  bathtub: Bath,
  desk: Lamp,
  wardrobe: Armchair,
  phone: Phone,
  soundproof: VolumeX,
  city_view: Building2,
  slippers: Footprints,
  bed: BedDouble,
};

export function AmenityIcon({ name, className = "h-4 w-4" }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Check;
  return <Icon aria-hidden className={className} strokeWidth={1.75} />;
}
